# Generated by Django 3.2.7 on 2021-10-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, default='', max_length=255, verbose_name='Subtitle')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'ExampleModel',
                'verbose_name_plural': 'ExampleModels',
            },
        ),
    ]
